OPM/IFEM-Darcy

- SIMDarcy.h
Requested by @VikingScientist.
Requires https://github.com/OPM/IFEM/pull/124
> Write velocities as a vector field in VTF output

- main_Darcy.C
> fixed: do not save initial state to VTF

- main_Darcy.C
Downstream of https://github.com/OPM/IFEM/pull/137
> adjust to upstream restarting changes

- main_Darcy.C
> Changed: handleDataOutput is now a SIMSolver member

- SIMDarcy.h
> Changed: solutionNorms signature for linear/static problems

- Darcy.h
- DarcySolutions.h
- SIMDarcy.h
- main_Darcy.C
Plus some small harmless static analyzer fixes.
> Fix some doxy issues

- Darcy.C
- Darcy.h
Some left-over things fra siste vårrengjøring..
> Changed: Some cleaning and micro-optimalization in the Darcy integrand, etc.

- Test/MPI/Lshape_p2_b5.reg
- Test/MPI/Lshape_p2_b5_adap.reg
> Removed error message from reg-files. It will go away soon.

- main_Darcy.C
Downstream of https://github.com/OPM/IFEM/pull/433
> solver template update - pass appropriate ProcessAdm

- SIMDarcy.h
> Changed: setNormPrefixes no longer needed

- CMakeLists.txt
- DarcySolutions.h
- SIMDarcy.h
Cosmetics and improved verbosity.
> Some small fixes

- Darcy.C
- Darcy.h
- DarcySolutions.C
- DarcySolutions.h
- SIMDarcy.h
- Test/Wavefront_k10_p2_b20.xinp
- avoid include in header
- use override. this allows me to detect an unused method.
> Some small cleanups

- CMakeLists.txt
- Darcy.C
- Darcy.h
- DarcyArgs.C
- DarcyArgs.h
- SIMDarcy.h
- Test/SimpleSquare.reg
- Test/SimpleSquare.xinp
- main_Darcy.C
> add time stepping support

- Common/Darcy/SIMDarcy.C
- Common/Darcy/SIMDarcy.h
- Common/Darcy/Test/TestSIMDarcy.C
- main_Darcy.C
To allow for using subclassed integrands.
> Use externally supplied integrand

- Common/Darcy/SIMDarcy.C
- Common/Darcy/SIMDarcy.h
> Changed: newLHS removed in solveSystem method

- Common/Darcy/MixedDarcy.C
Downstream of https://github.com/OPM/IFEM/pull/537
> changed: adjust to BlockElmMats change

- Common/Darcy/DarcySolutions.C
- Test/Dirac.reg
- Test/Dirac3D.reg
Most importantly, they're now normalized with integral 1.
> Diracsum fixes

- Common/Darcy/Darcy.C
- Common/Darcy/Darcy.h
- Common/Darcy/SIMDarcy.C
> Rename setReactionIntegral to setSecondaryInt and use SIMbase::assembleForces

- CMakeLists.txt
- Common/Darcy/CMakeLists.txt
To quell warnings on ubuntu jammy.
> changed: bump minimum cmake version

- CMakeLists.txt
- Common/Darcy/CMakeLists.txt
Downstream of https://github.com/OPM/IFEM/pull/559
> update unit test handling

- Common/Darcy/DarcySolutions.C
- Common/Darcy/DarcySolutions.h
> added: setParam to DiracSum function

- Common/Darcy/Darcy.C
- Common/Darcy/Darcy.h
- Common/Darcy/DarcyTransport.C
- Common/Darcy/SIMDarcy.C
- Common/Darcy/SIMDarcy.h
> added: support for element matrix cache

- CMakeLists.txt
- Common/Darcy/CMakeLists.txt
Same as https://github.com/OPM/IFEM/pull/618
> bump minimum cmake version and move required tag before project

- Common/Darcy/DarcySolutions.C
- Common/Darcy/DarcySolutions.h
- Common/Darcy/SIMDarcy.C
and avoid EvalFunction in header
> use unique_ptr

- Common/Darcy/DarcyMaterial.C
- Common/Darcy/DarcyMaterial.h
- Common/Darcy/SIMDarcy.C
- Common/Darcy/SIMDarcy.h
- Common/Darcy/SIMDarcyAdvection.C
- Common/Darcy/SIMDarcyAdvection.h
- Common/Darcy/SIMDarcySchedule.C
- Common/Darcy/SIMDarcySchedule.h
- DarcyArgs.C
- DarcyArgs.h
Downstream of https://github.com/OPM/IFEM/pull/661
> changed: tinyxml -> tinyxml2

- Test/SimpleSquare2p.reg
Downstream of https://github.com/OPM/IFEM/pull/667
> adjust regression tests for anasol print

- Common/Darcy/SIMDarcy.h
Wrong, and unnecessary, forward declaration
> Fixup for commit 242445d2f41ea28e63c1d9d3425ddac7e15dd92c

- Common/Darcy/Darcy.C
- Common/Darcy/DarcyAdvection.C
- Common/Darcy/DarcyAdvection.h
- Common/Darcy/DarcyTransport.C
- Common/Darcy/SIMDarcy.h
> Use RealArray as type for reaction force container and some temporaries

- Common/Darcy/CMakeLists.txt
Downstream of https://github.com/OPM/IFEM/pull/806
> adjust to new ifem_add_test_app api

- Common/Darcy/Test/TestSIMDarcy.C
Downstream of https://github.com/OPM/IFEM/pull/810
> convert unit-tests to catch
